name: pragma_game
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flame: ^1.21.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/elementos/
    - assets/images/elementos/escenario.png
    - assets/images/personaje/
    - assets/images/menu/
    - assets/images/HUD/

icons_launcher:
  image_path: "assets/images/personaje/Personaje-F0.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/personaje/Personaje-F0.png"
    ios:
      enable: true
      image_path: "assets/images/personaje/Personaje-F0.png"
      # For iOS 18+ (support dark and tinted)
    web:
      enable: true
      image_path: "assets/images/personaje/Personaje-F0.png"
    macos:
      enable: true
      image_path: "assets/images/personaje/Personaje-F0.png"
    windows:
      enable: true
      image_path: "assets/images/personaje/Personaje-F0.png"

